export const CONFIG = {
  grid: {
    cols: 24,
    rows: 14,
    cellSize: 40,
    minSpawnExitDistance: 22,
  },
  gameplay: {
    startingLives: 20,
    startingMoney: 260,
    startingBlockTiles: 42,
    blockTilesPerWave: 8,
    totalWaves: 10,
    victoryBonus: 140,
    waveClearBonus: 45,
  },
  towerOrder: ['pulse', 'nova', 'rail', 'shard'],
  enemyOrder: ['normal', 'runner', 'shielded', 'tank', 'swarm'],
  projectile: {
    speed: 420,
    novaExplosionDuration: 0.16,
  },
  towers: {
    pulse: {
      name: 'Pulse Tower',
      role: 'Fast single-target pressure',
      unlockWave: 1,
      color: '#2af6ff',
      cost: 90,
      levels: [
        { range: 2.7, fireRate: 2.3, damage: 15, projectileSpeed: 470, upgradeCost: 70, shotsPerAttack: 1, targetCount: 1 },
        { range: 3.0, fireRate: 2.7, damage: 21, projectileSpeed: 510, upgradeCost: 120, shotsPerAttack: 1, targetCount: 1 },
        { range: 3.4, fireRate: 3.0, damage: 29, projectileSpeed: 550, upgradeCost: null, shotsPerAttack: 1, targetCount: 1 },
      ],
    },
    nova: {
      name: 'Nova Tower',
      role: 'Slow splash burst',
      unlockWave: 1,
      color: '#ff2ac9',
      cost: 135,
      levels: [
        { range: 2.3, fireRate: 0.9, damage: 36, splashRadius: 1.0, projectileSpeed: 360, upgradeCost: 95, shotsPerAttack: 1, targetCount: 1 },
        { range: 2.5, fireRate: 1.05, damage: 50, splashRadius: 1.2, projectileSpeed: 390, upgradeCost: 155, shotsPerAttack: 1, targetCount: 1 },
        { range: 2.8, fireRate: 1.2, damage: 66, splashRadius: 1.4, projectileSpeed: 420, upgradeCost: null, shotsPerAttack: 1, targetCount: 1 },
      ],
    },
    rail: {
      name: 'Rail Tower',
      role: 'Long-range anti-armor shots',
      unlockWave: 3,
      color: '#ffd85a',
      cost: 155,
      levels: [
        { range: 3.8, fireRate: 0.58, damage: 76, projectileSpeed: 640, upgradeCost: 105, shotsPerAttack: 1, targetCount: 1 },
        { range: 4.1, fireRate: 0.66, damage: 98, projectileSpeed: 690, upgradeCost: 155, shotsPerAttack: 1, targetCount: 1 },
        { range: 4.45, fireRate: 0.74, damage: 126, projectileSpeed: 750, upgradeCost: null, shotsPerAttack: 1, targetCount: 1 },
      ],
    },
    shard: {
      name: 'Shard Tower',
      role: 'Multi-target swarm control',
      unlockWave: 6,
      color: '#7fff3a',
      cost: 125,
      levels: [
        { range: 2.35, fireRate: 1.35, damage: 12, projectileSpeed: 430, upgradeCost: 85, shotsPerAttack: 3, targetCount: 3 },
        { range: 2.6, fireRate: 1.55, damage: 16, projectileSpeed: 470, upgradeCost: 125, shotsPerAttack: 3, targetCount: 3 },
        { range: 2.85, fireRate: 1.78, damage: 21, projectileSpeed: 520, upgradeCost: null, shotsPerAttack: 4, targetCount: 4 },
      ],
    },
  },
  enemies: {
    normal: {
      name: 'Normal',
      unlockWave: 1,
      color: '#9e5bff',
      shape: 'diamond',
      size: 10,
      hp: 75,
      speed: 82,
      reward: 14,
      score: 30,
      armor: 0,
    },
    runner: {
      name: 'Runner',
      unlockWave: 1,
      color: '#7fff3a',
      shape: 'triangle',
      size: 9,
      hp: 48,
      speed: 126,
      reward: 10,
      score: 24,
      armor: 0,
    },
    shielded: {
      name: 'Shielded',
      unlockWave: 3,
      color: '#4ec5ff',
      shape: 'hexagon',
      size: 11,
      hp: 124,
      speed: 74,
      reward: 22,
      score: 42,
      armor: 6,
    },
    tank: {
      name: 'Tank',
      unlockWave: 4,
      color: '#ff8f2a',
      shape: 'square',
      size: 12,
      hp: 170,
      speed: 58,
      reward: 26,
      score: 50,
      armor: 2,
    },
    swarm: {
      name: 'Swarm',
      unlockWave: 6,
      color: '#ff5ef0',
      shape: 'circle',
      size: 7,
      hp: 24,
      speed: 148,
      reward: 7,
      score: 18,
      armor: 0,
    },
  },
};
