export const CONFIG = {
  grid: {
    cols: 18,
    rows: 12,
    cellSize: 48,
    minBuildableRatio: 0.58,
  },
  gameplay: {
    startingLives: 20,
    startingMoney: 220,
    totalWaves: 10,
    victoryBonus: 120,
    waveClearBonus: 40,
  },
  towerOrder: ['pulse', 'nova', 'rail', 'shard'],
  enemyOrder: ['normal', 'runner', 'shielded', 'tank', 'swarm'],
  pathGeneration: {
    retries: 90,
    minPathLength: 28,
    maxPathLength: 88,
    turnBias: 0.62,
  },
  projectile: {
    speed: 420,
    novaExplosionDuration: 0.16,
  },
  towers: {
    pulse: {
      name: 'Pulse Tower',
      role: 'Fast single-target pressure',
      unlockWave: 1,
      color: '#2af6ff',
      cost: 90,
      levels: [
        { range: 2.5, fireRate: 2.2, damage: 15, projectileSpeed: 460, upgradeCost: 70, shotsPerAttack: 1, targetCount: 1 },
        { range: 2.8, fireRate: 2.5, damage: 21, projectileSpeed: 500, upgradeCost: 120, shotsPerAttack: 1, targetCount: 1 },
        { range: 3.2, fireRate: 2.9, damage: 30, projectileSpeed: 540, upgradeCost: null, shotsPerAttack: 1, targetCount: 1 },
      ],
    },
    nova: {
      name: 'Nova Tower',
      role: 'Slow splash burst',
      unlockWave: 1,
      color: '#ff2ac9',
      cost: 130,
      levels: [
        { range: 2.2, fireRate: 0.95, damage: 34, splashRadius: 0.95, projectileSpeed: 360, upgradeCost: 90, shotsPerAttack: 1, targetCount: 1 },
        { range: 2.4, fireRate: 1.1, damage: 48, splashRadius: 1.15, projectileSpeed: 385, upgradeCost: 150, shotsPerAttack: 1, targetCount: 1 },
        { range: 2.7, fireRate: 1.25, damage: 65, splashRadius: 1.35, projectileSpeed: 420, upgradeCost: null, shotsPerAttack: 1, targetCount: 1 },
      ],
    },
    rail: {
      name: 'Rail Tower',
      role: 'Long-range anti-armor shots',
      unlockWave: 3,
      color: '#ffd85a',
      cost: 155,
      levels: [
        { range: 3.8, fireRate: 0.58, damage: 76, projectileSpeed: 640, upgradeCost: 105, shotsPerAttack: 1, targetCount: 1 },
        { range: 4.1, fireRate: 0.66, damage: 98, projectileSpeed: 690, upgradeCost: 155, shotsPerAttack: 1, targetCount: 1 },
        { range: 4.45, fireRate: 0.74, damage: 126, projectileSpeed: 750, upgradeCost: null, shotsPerAttack: 1, targetCount: 1 },
      ],
    },
    shard: {
      name: 'Shard Tower',
      role: 'Multi-target swarm control',
      unlockWave: 6,
      color: '#7fff3a',
      cost: 125,
      levels: [
        { range: 2.35, fireRate: 1.35, damage: 12, projectileSpeed: 430, upgradeCost: 85, shotsPerAttack: 3, targetCount: 3 },
        { range: 2.6, fireRate: 1.55, damage: 16, projectileSpeed: 470, upgradeCost: 125, shotsPerAttack: 3, targetCount: 3 },
        { range: 2.85, fireRate: 1.78, damage: 21, projectileSpeed: 520, upgradeCost: null, shotsPerAttack: 4, targetCount: 4 },
      ],
    },
  },
  enemies: {
    normal: {
      name: 'Normal',
      unlockWave: 1,
      color: '#9e5bff',
      shape: 'diamond',
      size: 10,
      hp: 70,
      speed: 78,
      reward: 15,
      score: 30,
      armor: 0,
    },
    runner: {
      name: 'Runner',
      unlockWave: 1,
      color: '#7fff3a',
      shape: 'triangle',
      size: 9,
      hp: 45,
      speed: 120,
      reward: 11,
      score: 25,
      armor: 0,
    },
    shielded: {
      name: 'Shielded',
      unlockWave: 3,
      color: '#4ec5ff',
      shape: 'hexagon',
      size: 11,
      hp: 122,
      speed: 74,
      reward: 22,
      score: 42,
      armor: 6,
    },
    tank: {
      name: 'Tank',
      unlockWave: 4,
      color: '#ff8f2a',
      shape: 'square',
      size: 12,
      hp: 172,
      speed: 56,
      reward: 26,
      score: 48,
      armor: 2,
    },
    swarm: {
      name: 'Swarm',
      unlockWave: 6,
      color: '#ff5ef0',
      shape: 'circle',
      size: 7,
      hp: 24,
      speed: 148,
      reward: 7,
      score: 18,
      armor: 0,
    },
  },
};
